// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgDI_k89L6Bv2Tskr87kjWDUkIC6EH0Q',
    appId: '1:789976747725:android:afb5d48bf2c877af1e2384',
    messagingSenderId: '789976747725',
    projectId: 'testefirebase-951ee',
    databaseURL: 'https://testefirebase-951ee.firebaseio.com',
    storageBucket: 'testefirebase-951ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxnIW1PuBHPk_PKHoBP0vwa6f3QsVELI',
    appId: '1:789976747725:ios:07fbeec79cc7a3941e2384',
    messagingSenderId: '789976747725',
    projectId: 'testefirebase-951ee',
    databaseURL: 'https://testefirebase-951ee.firebaseio.com',
    storageBucket: 'testefirebase-951ee.firebasestorage.app',
    iosBundleId: 'br.com.flutterdicas.moviesapp.firebaseMoviesApp',
  );
}
